modLoader = "javafml"
loaderVersion = "[4,)"
license = "${mod_license}"
issueTrackerURL = "https://github.com/kouchamadanai-netizen/Cobblemon_PXS/issues"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
logoFile = "logo.png"
description = '''
${mod_description}
${mod_declaration}
'''
authors = "${mod_authors}"

[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "cobblemon"
type = "required"
versionRange = "[1.6.0,)"
ordering = "NONE"
side = "BOTH"
